apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-recommender-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime-recommender-app
  template:
    metadata:
      labels:
        app: anime-recommender-app
    spec:
      containers:
      - name: anime-recommender-app-container
        image: gcr.io/mlops-projects-457610/anime-project:latest
        ports:
        - containerPort: 5000  # Replace with the port your app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: anime-recommender-app-service
spec:
  type: LoadBalancer
  selector:
    app: anime-recommender-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000